version: "3"
services:
  react:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
# 참고 : https://velog.io/@rmswjdtn/Docker-%EB%8F%84%EC%BB%A4%EB%A1%9C-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%95%B1-%EC%8B%A4%ED%96%89-by-%EB%94%B0%EB%9D%BC%ED%95%98%EB%A9%B0-%EB%B0%B0%EC%9A%B0%EB%8A%94-Docker%EC%99%80-CI%ED%99%98%EA%B2%BD
